[package]
name = "axum-sqlx-postgresql"
version = "0.1.0"
edition = "2024"

[dependencies]
# Server
axum = "0.8.4"
tokio = { version = "1.45.0", features = ["full"] }

# Database
sqlx = { version = "0.8.5", features = ["runtime-tokio", "postgres"] }

# Others
dotenvy = "0.15.7"
